"""Added language column to comments

Revision ID: 28660f94166d
Revises: de9115c07eab
Create Date: 2022-12-09 21:18:57.594787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28660f94166d'
down_revision = 'de9115c07eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
