"""Added unique urls for images in User and Post

Revision ID: 39c4d8785063
Revises: d46f265acb5a
Create Date: 2022-12-08 20:48:13.645186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c4d8785063'
down_revision = 'd46f265acb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_image', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_profile_pic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unique_cover_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unique_cover_pic')
        batch_op.drop_column('unique_profile_pic')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('unique_image')

    # ### end Alembic commands ###
