"""Altered comments name in post to avoid conflict

Revision ID: f9512997317d
Revises: ff51372f6282
Create Date: 2022-12-05 12:36:14.876475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9512997317d'
down_revision = 'ff51372f6282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_allowed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('comments_allowed')

    # ### end Alembic commands ###
